name: MLOps CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: iterative/setup-dvc@v1
      - run: pip install -r requirements.txt
      - run: dvc pull
      - run: python -m pytest